# adapted from makefile by Prof. Phillip Colella
# 27 Sept. 2018



HOME = ./..


include $(HOME)/GNUmakefile



# recipe for main method
main: GNUmakefile $(OBJS) 
	$(CXX) $(CFLAGS) $(CALCFLAGS) $(OBJS) -o activeContact.exe

